# Generated by Django 4.0.4 on 2022-05-27 10:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromAirport', models.CharField(max_length=4)),
                ('toAirport', models.CharField(max_length=4)),
                ('leavingDate', models.DateTimeField(default=datetime.datetime(2022, 5, 27, 10, 6, 33, 39103, tzinfo=utc))),
                ('arrivalDate', models.DateTimeField(default=datetime.datetime(2022, 5, 27, 10, 6, 33, 39103, tzinfo=utc))),
                ('flightNo', models.IntegerField(default=0)),
                ('planeType', models.CharField(default='Plane', max_length=20)),
                ('remainingSeats', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Flights',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('flightNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flights')),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
    ]
