# Generated by Django 4.0.4 on 2022-05-27 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='arrivalDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 10, 6, 48, 653696, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='flights',
            name='leavingDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 10, 6, 48, 653696, tzinfo=utc)),
        ),
    ]
