# Generated by Django 4.0.4 on 2022-05-31 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_flights_stopovers_alter_flights_arrivaldate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='arrivalDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 4, 29, 15, 341744, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='flights',
            name='leavingDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 4, 29, 15, 341744, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='flights',
            name='stopOvers',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
