# Generated by Django 4.0.4 on 2022-06-01 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_flights_arrivaldate_alter_flights_leavingdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='bookingNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flights',
            name='arrivalDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 23, 6, 44, 296560)),
        ),
        migrations.AlterField(
            model_name='flights',
            name='leavingDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 23, 6, 44, 296560)),
        ),
    ]
